<a href="https://colab.research.google.com/github/TheTechArtist-Varni/social__sentiment/blob/main/weather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Analyzing weather data using a CSV file and basic Pandas commands**

Importing pandas in order to use in built functions

In [1]:
import pandas as pd

Reading the
 csv file

In [2]:
data= pd.read_csv("/content/weatherHistory.csv")

Partially viewing the dataset

In [3]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

**How to analyze data frames**

Viewing the first 'n' rows of dataset here n = 5

In [4]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

Viewing the number of rows and columns in the dataset

In [5]:
data.shape

(96453, 12)

Viewing the Range of the dataset

In [6]:
data.index

RangeIndex(start=0, stop=96453, step=1)

Viewing dataset column names

In [7]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

Viewing the datatypes of each column

In [8]:
data.dtypes

Formatted Date               object
Summary                      object
Precip Type                  object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Loud Cover                  float64
Pressure (millibars)        float64
Daily Summary                object
dtype: object

Viewing number of non null data in each column

In [34]:
 data.count()

Formatted Date              96453
Summary                     96453
Precip Type                 95936
Temperature (C)             96453
Apparent Temperature (C)    96453
Humidity                    96453
Wind Speed (km/h)           96453
Wind Bearing (degrees)      96453
Visibility (km)             96453
Loud Cover                  96453
Pressure (millibars)        96453
Weather                     96453
dtype: int64

Finding out the unique values in Summary column

In [35]:
data['Summary'].unique()

array(['Partly Cloudy', 'Mostly Cloudy', 'Overcast', 'Foggy',
       'Breezy and Mostly Cloudy', 'Clear', 'Breezy and Partly Cloudy',
       'Breezy and Overcast', 'Humid and Mostly Cloudy',
       'Humid and Partly Cloudy', 'Windy and Foggy', 'Windy and Overcast',
       'Breezy and Foggy', 'Windy and Partly Cloudy', 'Breezy',
       'Dry and Partly Cloudy', 'Windy and Mostly Cloudy',
       'Dangerously Windy and Partly Cloudy', 'Dry', 'Windy',
       'Humid and Overcast', 'Light Rain', 'Drizzle', 'Windy and Dry',
       'Dry and Mostly Cloudy', 'Breezy and Dry', 'Rain'], dtype=object)

 The number of unique  values in each column

In [11]:
 data.nunique()

Formatted Date              96429
Summary                        27
Precip Type                     2
Temperature (C)              7574
Apparent Temperature (C)     8984
Humidity                       90
Wind Speed (km/h)            2484
Wind Bearing (degrees)        360
Visibility (km)               949
Loud Cover                      1
Pressure (millibars)         4979
Daily Summary                 214
dtype: int64

Basic information about the dataset

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

# QUESTIONS AND ANSWERS
1. Find all unique "windspeed" values

In [16]:
data['Wind Speed (km/h)'].unique()

array([14.1197, 14.2646,  3.9284, ..., 37.0622, 35.5971, 30.751 ])

2. Find number of times 9.9820
is the visibility

In [17]:
filtered_data = data[data['Visibility (km)'] == '9.9820']

3.Find the no of timed windspeed was 4km/h

In [18]:
data['Wind Speed (km/h)'].unique()

array([14.1197, 14.2646,  3.9284, ..., 37.0622, 35.5971, 30.751 ])

In [19]:
data[data['Wind Speed (km/h)']=='4']

Empty DataFrame
Columns: [Formatted Date, Summary, Precip Type, Temperature (C), Apparent Temperature (C), Humidity, Wind Speed (km/h), Wind Bearing (degrees), Visibility (km), Loud Cover, Pressure (millibars), Daily Summary]
Index: []

In [20]:
data.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [21]:
data.rename(columns={'Daily Summary':'Weather'},inplace=True)

In [22]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

4. What is the mean Humidity?

In [23]:
data.Humidity.mean()

np.float64(0.7348989663359355)

5. What is the standarad deviation of Humidity

In [24]:
data.Humidity.std()

0.19547273906722662

6. Find  the variance of summary

In [25]:
data['Humidity'].dtype

dtype('float64')

In [26]:
data['Humidity'].var()

0.03820959171844407

7. Find all instances when rain was recorded

In [27]:
data[data['Precip Type']=='rain']

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

8. Find all the instances where wind speed>24 and visibility>25

In [28]:
(data['Wind Speed (km/h)']>24)&(data['Visibility (km)']>25)

0        False
1        False
2        False
3        False
4        False
         ...
96448    False
96449    False
96450    False
96451    False
96452    False
Length: 96453, dtype: bool

9. Find the mean value of each column against Weather

In [29]:
data.groupby('Humidity').mean(numeric_only=True)

,Temperature (C),Apparent Temperature (C),Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
Humidity,,,,,,,
0.00,-13.560606,-17.626263,9.568523,110.545455,6.659545,0.0,1028.333636
0.12,13.888889,13.888889,28.980000,10.000000,9.982000,0.0,1028.000000
0.13,39.905556,37.538889,23.586500,250.000000,9.982000,0.0,1007.550000
0.14,32.637500,30.873611,15.415750,132.500000,10.074575,0.0,1016.712500
0.15,25.514444,23.225000,18.880470,181.300000,11.318300,0.0,1016.724000
...,...,...,...,...,...,...,...
0.96,5.595618,4.289998,7.590989,177.013531,5.674167,0.0,1010.848012
0.97,13.613889,13.124532,6.666064,187.853952,7.732343,0.0,1011.898196
0.98,5.327339,3.922749,7.739709,190.478261,5.308673,0.0,1019.139723
0.99,4.650046,3.248368,7.588719,187.324239,4.650040,0.0,1013.055070
1.00,4.502276,3.049792,7.586292,174.726990,3.312578,0.0,996.655599

10. Find min and max values of each column against Humidity

In [30]:
data.groupby('Humidity')['Temperature (C)'].max()

Humidity
0.00     1.111111
0.12    13.888889
0.13    39.905556
0.14    38.983333
0.15    39.588889
          ...
0.96    22.688889
0.97    21.583333
0.98    22.138889
0.99    22.088889
1.00    21.555556
Name: Temperature (C), Length: 90, dtype: float64

In [31]:
data.groupby('Humidity')['Temperature (C)'].min()

Humidity
0.00   -17.777778
0.12    13.888889
0.13    39.905556
0.14    15.000000
0.15     1.133333
          ...
0.96   -13.194444
0.97    -5.988889
0.98    -9.161111
0.99   -14.005556
1.00    -8.888889
Name: Temperature (C), Length: 90, dtype: float64

11. Show all records when weather is 'Partly cloudy throughout the day.'

In [32]:
data[data['Weather']== 'Partly cloudy throughout the day.']

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96400,2016-09-07 19:00:00.000 +0200,Partly Cloudy,rain,23.838889,23.838889,0.62,3.2200,70.0,16.1000,0.0,1018.95,Partly cloudy throughout the day.
96401,2016-09-07 20:00:00.000 +0200,Partly Cloudy,rain,21.005556,21.005556,0.73,0.3220,10.0,15.5526,0.0,1019.43,Partly cloudy throughout the day.
96402,2016-09-07 21:00:00.000 +0200,Partly Cloudy,rain,19.838889,19.838889,0.79,3.2200,40.0,16.1000,0.0,1019.83,Partly cloudy throughout the day.
96403,2016-09-07 22:00:00.000 +0200,Partly Cloudy,rain,18.727778,18.727778,0.84,0.0000,0.0,16.1000,0.0,1019.64,Partly cloudy throughout the day.
96404,2016-09-07 23:00:00.000 +0200,Partly Cloudy,rain,17.661111,17.661111,0.88,3.2200,10.0,15.1501,0.0,1019.39,Partly cloudy throughout the day.

12. Find all instances when 'weather' is 'Partly cloudy throughout the day.'or visibility>40

In [36]:
data[
    (data['Weather'] == 'Partly cloudy throughout the day.') |
    (data['Visibility (km)'] > 40)
]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96400,2016-09-07 19:00:00.000 +0200,Partly Cloudy,rain,23.838889,23.838889,0.62,3.2200,70.0,16.1000,0.0,1018.95,Partly cloudy throughout the day.
96401,2016-09-07 20:00:00.000 +0200,Partly Cloudy,rain,21.005556,21.005556,0.73,0.3220,10.0,15.5526,0.0,1019.43,Partly cloudy throughout the day.
96402,2016-09-07 21:00:00.000 +0200,Partly Cloudy,rain,19.838889,19.838889,0.79,3.2200,40.0,16.1000,0.0,1019.83,Partly cloudy throughout the day.
96403,2016-09-07 22:00:00.000 +0200,Partly Cloudy,rain,18.727778,18.727778,0.84,0.0000,0.0,16.1000,0.0,1019.64,Partly cloudy throughout the day.
96404,2016-09-07 23:00:00.000 +0200,Partly Cloudy,rain,17.661111,17.661111,0.88,3.2200,10.0,15.1501,0.0,1019.39,Partly cloudy throughout the day.